label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_POLICY_SUBJECT_DUPLICATE_LABEL
name: check_policy_subject_duplicate
format: rawlist
template: >
  [% USE Certificate %]
  [% IF value %]
    Expiry / Identifier |
    [% FOREACH identifier = value %]
      <a target="modal" href="#certificate!detail!identifier![% identifier %]">
        [% Certificate.notafter(identifier) %] / [% identifier %]</a>|
    [% END %]
  [% END %]
