head:
    prefix: enroll
    label: I18N_OPENXPKI_UI_WORKFLOW_TYPE_CERT_ENROLL_LABEL
    description: I18N_OPENXPKI_UI_WORKFLOW_TYPE_CERT_ENROLL_DESC

state:
    INITIAL:
        action: initialize global_load_policy set_profile parse_pkcs10 render_subject > CREATED

    CREATED:
        autorun: 1
        action:
          - global_check_authorized_signer > CHECK_AUTHORIZATION ? global_is_signed_request
          - global_set_error_not_authenticated > FAILURE ? !is_manual_authentication_allowed !global_is_signed_request
          - global_noop > MANUAL_APPROVAL ? !global_is_signed_request is_manual_authentication_allowed


    CHECK_AUTHORIZATION:
        autorun: 1
        action:
          - global_set_error_signer_not_authorized > MANUAL_AUTHORIZATION ? !is_requestor_authorized is_manual_authentication_allowed
          - global_set_error_signer_not_authorized > FAILURE ? !is_requestor_authorized !is_manual_authentication_allowed
          - global_set_error_signer_expired > FAILURE ? is_requestor_authorized !is_requestor_validity_ok
          - global_set_error_signer_revoked > FAILURE ? is_requestor_revoked is_requestor_authorized is_requestor_validity_ok
          - global_noop > AUTHORIZED ? is_requestor_authorized !is_requestor_revoked is_requestor_validity_ok

    MANUAL_AUTHORIZATION:
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_ENROLL_MANUAL_AUTHORIZATION_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_ENROLL_MANUAL_AUTHORIZATION_DESC
        action:
          - reject_request > FAILURE
          - accept_request > AUTHORIZED
        output:
          - server
          - interface
          - csr_subject
          - comment
          - cert_profile
          - signer_cert_identifier
          - signer_revoked
          - signer_trusted
          - signer_authorized
          - signer_validity_ok

        button:
          accept_request:
            format: expected
          reject_request:
            format: failure

    AUTHORIZED:
        autorun: 1
        action: global_noop > PERFORM_POLICY_CHECK

    PERFORM_POLICY_CHECK:
        autorun: 1
        action: global_noop > CHECK_POLICY_VIOLATION

    CHECK_POLICY_VIOLATION:
        autorun: 1
        action:
          - global_set_error_code_policy_violated > PENDING_POLICY ? has_policy_violations
          - global_noop > ELIGIBILITY ? !has_policy_violations

    PENDING_POLICY:
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_ENROLL_PENDING_POLICY_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_ENROLL_PENDING_POLICY_DESC
        action:
          - reevaluate_policy > PERFORM_POLICY_CHECK
          - override_policy > ELIGIBILITY
          - reject_request global_set_error_rejected > FAILURE
        button:
          override_policy:
            format: alternative
          reevaluate_policy:
            format: expected
          reject_request:
            format: failure

    ELIGIBILITY:
        autorun: 1
        action: check_eligibility > EVALUATE_AUTOAPPROVAL

    EVALUATE_AUTOAPPROVAL:
        autorun: 1
        action:
         - approve_by_eligiblity calculate_approval_points > CHECK_APPROVAL ? is_eligible
         - calculate_approval_points > CHECK_APPROVAL ? !is_eligible

    CHECK_APPROVAL:
        autorun: 1
        action:
         - notify_approval_pending global_set_error_not_approved > PENDING ? !is_approved is_manual_approval_allowed
         - notify_rejected global_set_error_rejected > FAILURE ? !is_approved !is_manual_approval_allowed
         - global_clear_error_code > APPROVED ? is_approved

    PENDING:
       action:
        - reject_request notify_rejected global_set_error_rejected > FAILURE
        - approve_csr calculate_approval_points > RECHECK_APPROVAL

    RECHECK_APPROVAL:
        autorun: 1
        action:
         - global_set_error_not_approved > PENDING ? !is_approved
         - global_clear_error_code > APPROVED ? is_approved

    APPROVED:
        autorun: 1
        action: persist_csr > PREPARED

    PREPARED:
        autorun: 1
        action:
          - global_nice_issue_certificate > SUCCESS

    SUCCESS:
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_ENROLL_SUCCESS_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_ENROLL_SUCCESS_DESC

    FAILURE:
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_CSR_FAILURE_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_CSR_FAILURE_DESC

action:
    initialize:
        class: OpenXPKI::Server::Workflow::Activity::Tools::SetSource
        param:
            source: api
        input:
            - pkcs10
            - server
            - interface
#            - csr_subject
            - signer_cert
            - comment
#            - cert_profile

    accept_request:
        class: OpenXPKI::Server::Workflow::Activity::Noop
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_ENROLL_ACCEPT_REQUEST_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_ENROLL_ACCEPT_REQUEST_DESC

    reject_request:
        class: OpenXPKI::Server::Workflow::Activity::Noop
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CSR_REJECT_REQUEST_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CSR_REJECT_REQUEST_DESC

    approve_csr:
        class: OpenXPKI::Server::Workflow::Activity::Tools::Approve
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CSR_APPROVE_CSR_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_APPROVE_CSR_DESC

    override_policy:
        class: OpenXPKI::Server::Workflow::Activity::Noop
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_ENROLL_OVERRIDE_POLICY_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_ENROLL_OVERRIDE_POLICY_DESC

    reevaluate_policy:
        class: OpenXPKI::Server::Workflow::Activity::Tools::SetContext
        param:
            check_policy_duplicate: ''
            check_policy_dns: ''

    check_eligibility:
        class: OpenXPKI::Server::Workflow::Activity::Tools::EvaluateEligibility
        param:
            _map_config_path: "[% context.interface %].[% context.server %].eligibility"
            target_key: is_eligible
            raw_result: eligibility_result

    approve_by_eligiblity:
        class: OpenXPKI::Server::Workflow::Activity::Tools::Approve
        param:
            mode: generated
            _map_comment: "Auto-Approval based on eligibility result: [% context.eligibility_result %]"

    calculate_approval_points:
        class: OpenXPKI::Server::Workflow::Activity::Tools::CalculateApprovalPoints

    notify_approval_pending:
        class: OpenXPKI::Server::Workflow::Activity::Tools::Notify
        param:
            message: enroll_notify_approval_pending

    persist_csr:
        class: OpenXPKI::Server::Workflow::Activity::CSR::PersistRequest
        param:
            csr_type: pkcs10

    parse_pkcs10:
        class: OpenXPKI::Server::Workflow::Activity::Tools::ParsePKCS10

    render_subject:
        class: OpenXPKI::Server::Workflow::Activity::Tools::RenderSubject
        param:
            cert_subject_style: enroll

    set_profile:
        class: OpenXPKI::Server::Workflow::Activity::Tools::Connector::GetValue
        param:
            mode: hash
            _map_config_path: "[% context.interface %].[% context.server %].profile"

condition:
    is_requestor_authorized:
        class: Workflow::Condition::Evaluate
        param:
            test: ($context->{signer_trusted} and $context->{signer_authorized})

    is_requestor_validity_ok:
        class: Workflow::Condition::Evaluate
        param:
            test: ($context->{signer_validity_ok})

    is_requestor_revoked:
        class: Workflow::Condition::Evaluate
        param:
            test: ($context->{signer_revoked})

    is_manual_authentication_allowed:
        class: Workflow::Condition::Evaluate
        param:
            test: $context->{p_allow_man_authen};

    is_manual_approval_allowed:
        class: Workflow::Condition::Evaluate
        param:
            test: $context->{p_allow_man_approv};

    has_policy_violations:
        class: Workflow::Condition::Evaluate
        param:
            test: ($context->{check_policy_dns} || $context->{check_policy_duplicate});

    is_eligible:
        class: Workflow::Condition::Evaluate
        param:
            test: $context->{is_eligible}

    is_approved:
        class: Workflow::Condition::Evaluate
        param:
            test: $context->{approval_points} >= $context->{p_approval_points}


acl:
    Anonymous:
        creator: self

    CA Operator:
        creator: any

    RA Operator:
        creator: any
        fail: 1
        resume: 1
        wakeup: 1
        history: 1
        techlog: 1
        context: 1


    System:
        creator: self

    User:
        creator: self
