head:
    prefix: estenroll
    persister: Volatile

state:
    INITIAL:
        action: initialize parse_request set_profile render_subject persist_csr global_nice_issue_certificate > SUCCESS

    SUCCESS: ~

action:
    initialize:
        class: OpenXPKI::Server::Workflow::Activity::Noop
        input:
          - server
          - interface
          - pkcs10

    set_profile:
        class: OpenXPKI::Server::Workflow::Activity::Tools::SetContext
        param:
            cert_profile: I18N_OPENXPKI_PROFILE_TLS_SERVER
            cert_subject_style: enroll

    parse_request:
        class: OpenXPKI::Server::Workflow::Activity::Tools::ParsePKCS10
        param:
            req_extensions: certificateTemplate certificateTemplateName challengePassword

    render_subject:
        class: OpenXPKI::Server::Workflow::Activity::Tools::RenderSubject


    persist_csr:
        class: OpenXPKI::Server::Workflow::Activity::CSR::PersistRequest
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CSR_PERSIST_CSR_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CSR_PERSIST_CSR_DESC


acl:
    System:
        creator: any
        context: 1

    RA Operator:
        creator: any
        context: 1

